# Generated by Django 5.2.4 on 2025-07-31 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_purchased',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
